---
title: "Lab8_CkitrinosMArkdown"
output: html_document
---


# NG Phylogeny PNG file

##Phylogenetic analysis wss conducted at NGPhylogeny.fr. Sequences were aligned using MAFFT and the tree was produced using FastME.


```{r ,echo=FALSE}
library(png)
library(grid)
img <- readPNG("NGPHYTREE.png")
 grid.raster(img)

```



# Uploading Packages

```{r}
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install(version = "3.11")

```

```{r}
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("ggtree")
```

```{r}
library(tidyverse)
library(ggtree)
# added treeio and ggimage library
library(treeio)
library(ggimage)
# need to install libmagick 
#sudo apt-get install libmagick++-dev
```

```{r}
library(tidyverse)
library(ggtree)
tree <- read.tree("tree_newick.nwk")
tree
```

```{r}
# build a ggplot with a geom_tree
ggplot(tree) + geom_tree() + theme_tree()
# This is convenient shorthand
ggtree(tree)
```

```{r}
# add a scale
ggtree(tree) + geom_treescale()
# or add the entire scale to the x axis with theme_tree2()
ggtree(tree) + theme_tree2()
```

```{r}
ggtree(tree, branch.length="none")
```

```{r}
ggtree(tree, branch.length="none", color="blue", size=2, linetype=3)
```

```{r}
?ggtree
```

# Exercise 1

## 1: 

```{r}
ggplot(tree) + geom_tree() + theme_tree()
# This is convenient shorthand
ggtree(tree)

ggtree(tree, layout = "slanted")
```

##2:

```{r}
ggplot(tree) + geom_tree() + theme_tree()
# This is convenient shorthand
ggtree(tree)

ggtree(tree, layout = "circular")
```

##3:

```{r}
ggtree(tree, branch.length="none", color="red", size=2)
```

```{r}
# create the basic plot
p <- ggtree(tree)
# add node points
p + geom_nodepoint()
# add tip points
np <- p + geom_tippoint(shape = "diamond", color= "purple")
# Label the tips
mnp <- np + geom_tiplab( color="purple")
```

```{r}
qmnp <-mnp + geom_nodepoint(alpha=.4, color ="gold", size=4)
```

```{r}
qmnp + ggtitle("Phylogeny")
```

```{r}
ggtree(tree) + geom_text(aes(label=node), hjust=-.3)
```

```{r}
ggtree(tree) + geom_tiplab()

```

```{r}
MRCA(tree, c("C", "E"))
```

```{r}
MRCA(tree, c("G", "H"))
```

# Labelling Clades

```{r}
ggtree(tree) + 
  geom_cladelabel(node=17, label="Some random clade", color="red")
```

```{r}
ggtree(tree) + 
  geom_tiplab() + 
  geom_cladelabel(node=17, label="Some random clade", 
                  color="red2", offset=.8)
```

```{r}
ggtree(tree) + 
  geom_tiplab() + 
  geom_cladelabel(node=17, label="Some random clade", 
                  color="red2", offset=.8) + 
  geom_cladelabel(node=21, label="A different clade", 
                  color="blue", offset=.8, align = TRUE)
```

```{r}
ggtree(tree) + 
  geom_tiplab() + 
  geom_cladelabel(node=17, label="Some random clade", 
                  color="red2", offset=.8, align=TRUE) + 
  geom_cladelabel(node=21, label="A different clade", 
                  color="blue", offset=.8, align=TRUE) + 
  theme_tree2() + 
  xlim(0, 70) + 
  theme_tree()
```

```{r}
ggtree(tree) + 
  geom_tiplab() + 
  geom_hilight(node=17, fill="gold") + 
  geom_hilight(node=21, fill="purple")
```

# Connecting Taxa

```{r}
ggtree(tree) + 
  geom_tiplab() + 
  geom_taxalink("E", "H", color="blue3") +
  geom_taxalink("C", "G", color="orange2", curvature=-.9)
```

# Excercise 3

##1:

```{r}
MRCA(tree, c("B", "C"))
```

```{r}
MRCA(tree, c("L", "J"))
```

##2: 
```{r}
ggtree(tree)
```

##3:

```{r}
w <- ggtree(tree)

w + geom_tiplab( color="pink")
```

##4:

```{r}
w + 
  geom_tiplab() + 
  geom_hilight(node=19, fill="gold") + 
  geom_hilight(node=23, fill="pink")
```

##5: 

```{r}

rw <- w + 
  geom_tiplab() + 
  geom_hilight(node=19, fill="gold") + 
  geom_hilight(node=23, fill="pink") +
geom_cladelabel(node=17, label="Some random clade", 
                  color="orange", offset=.8, align=TRUE) + 
  theme_tree2() + 
  xlim(0, 70) + 
  theme_tree()

rw
```

##6: 

```{r}
rw + 
  geom_taxalink("C", "E", color="gray", linetype=2) +
  geom_taxalink("G", "J", color="gray", curvature=-.9, linetype=2)
```

##7:

```{r}
ewr <- rw + 
  geom_taxalink("C", "E", color="gray", linetype=2) +
  geom_taxalink("G", "J", color="gray", curvature=-.9, linetype=2) +
theme_tree2()

ewr
```

##8: 

```{r}
ewr + ggtitle("Phylogeny")
```

##8: 

```{r}
ggtree(tree, layout = "circular")+ 
geom_tiplab(color="pink") + 
  geom_hilight(node=19, fill="gold") + 
  geom_hilight(node=23, fill="pink") +
  geom_cladelabel(node=17, label="Superclade 17", 
                  color="orange", offset=.8, align=TRUE) + 
  theme_tree2() + 
  xlim(0, 70) + 
  theme_tree() +
  geom_taxalink("C", "E", color="gray", linetype=2) +
  geom_taxalink("G", "J", color="gray", curvature=-.9, linetype=2) +
theme_tree2() +
  ggtitle("Phylogeny")
```

# Bonus: 

```{r}
# Generate a random tree with 30 tips
tree <- rtree(30)
# Make the original plot
p <- ggtree(tree)
# generate some random values for each tip label in the data
d1 <- data.frame(id=tree$tip.label, val=rnorm(30, sd=3))
# Make a second plot with the original, naming the new plot "dot", 
# using the data you just created, with a point geom.
p2 <- facet_plot(p, panel="dot", data=d1, geom=geom_point, aes(x=val), color='red3')
# Make some more data with another random value.
d2 <- data.frame(id=tree$tip.label, value = abs(rnorm(30, mean=100, sd=50)))
# Now add to that second plot, this time using the new d2 data above, 
# This time showing a bar segment, size 3, colored blue.
p3 <- facet_plot(p2, panel='bar', data=d2, geom=geom_segment, 
           aes(x=0, xend=value, y=y, yend=y), size=3, color='blue4') 
# Show all three plots with a scale
p3 + theme_tree2()

```

```{r}
# get phylopic 

newick <- "((Pongo_abelii,(Gorilla_gorilla_gorilla,(Pan_paniscus,Pan_troglodytes)Pan,Homo_sapiens)Homininae)Hominidae,Nomascus_leucogenys)Hominoidea;"

tree <- read.tree(text=newick)

d <- ggimage::phylopic_uid(tree$tip.label)
d$body_mass = c(52, 114, 47, 45, 58, 6)

p <- ggtree(tree) %<+% d + 
  geom_tiplab(aes(image=uid, colour=body_mass), geom="phylopic", offset=2.5,  alpha=.6) +
  geom_tiplab(aes(label=label), offset = .2, alpha=.4) + xlim(NA, 7) +
  scale_color_viridis_c(alpha=.4)
p  
```

```{r}
set.seed(42)
trees <- lapply(rep(c(10, 25, 50, 100), 3), rtree)
class(trees) <- "multiPhylo"
ggtree(trees) + facet_wrap(~.id, scale="free", ncol=4) + ggtitle("Many trees. Such phylogenetics. Wow.")
```
# CIPRES Tree

```{r}
ctree=read.tree("fastree_result.tre.txt")
ctree
```

```{r}
ggplot(ctree) + geom_tree() + theme_tree() 
# This is convenient shorthand
ggtree(ctree) +
  geom_tiplab(hjust=-.1, size = 3)  + geom_hilight(node=25, fill="gold", extend = 0.5) + geom_hilight(node=30, fill="pink", extend = 0.5) + geom_hilight(node=22, fill="orange", extend = 0.5, alpha=.3) 
```




